# Generated by Django 2.0.3 on 2018-10-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('is_projector', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_sali',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_rezerwacyjny.Sala'),
        ),
    ]
